version: '3.8'

services:
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4567
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    networks:
      - everwrite-network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4567:4567"
    volumes:
      - ./backend:/backend
    networks:
      - everwrite-network
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    networks:
      - everwrite-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passwd
    volumes:
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks: 
  everwrite-network:
    driver: bridge
    name: everwrite-network

volumes:
  mongo:
