apiVersion: v1
kind: Secret
metadata:
  name: mongodb-connection-secret
type: Opaque
data:
  url: bW9uZ29kYjovL3Jvb3Q6cGFzc3dkQGV2ZXJ3cml0ZS1tb25nb2RiLXNlcnZpY2UuZXZlcndyaXRlLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3
